apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ecommerce-go-dev

build:
  tagPolicy: { sha256: {} }
  local:
    push: false
    useBuildkit: false
  artifacts:
    - image: sokol111/ecommerce-product-service
      context: ..
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.local
        buildArgs:
          SERVICE_DIR: ecommerce-product-service
    - image: sokol111/ecommerce-category-service
      context: ..
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.local
        buildArgs:
          SERVICE_DIR: ecommerce-category-service
    - image: sokol111/ecommerce-product-query-service
      context: ..
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.local
        buildArgs:
          SERVICE_DIR: ecommerce-product-query-service
    - image: sokol111/ecommerce-category-query-service
      context: ..
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.local
        buildArgs:
          SERVICE_DIR: ecommerce-category-query-service
    
    - image: sokol111/ecommerce-product-service-migrator
      context: ..
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.migrations
        buildArgs:
          SERVICE_DIR: ecommerce-product-service
    - image: sokol111/ecommerce-category-service-migrator
      context: ..
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.migrations
        buildArgs:
          SERVICE_DIR: ecommerce-category-service
    - image: sokol111/ecommerce-product-query-service-migrator
      context: ..
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.migrations
        buildArgs:
          SERVICE_DIR: ecommerce-product-query-service
    - image: sokol111/ecommerce-category-query-service-migrator
      context: ..
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.migrations
        buildArgs:
          SERVICE_DIR: ecommerce-category-query-service
    - image: sokol111/ecommerce-commons-migrator
      context: ..
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.migrations
        buildArgs:
          SERVICE_DIR: ecommerce-commons

deploy:
  kubeContext: k3d-dev-cluster
  helm:
    releases:
      - name: traefik-crds
        remoteChart: traefik-crds
        repo: https://traefik.github.io/charts
        version: "1.11.0"
        namespace: traefik
        createNamespace: true
        wait: true
        upgradeOnChange: false

      - name: traefik
        remoteChart: traefik
        repo: https://traefik.github.io/charts
        version: "37.1.0"
        namespace: traefik
        valuesFiles: [helm/helm-values/traefik.yaml]
        wait: true
        upgradeOnChange: false
        dependsOn: ["traefik-crds"]

      - name: loki
        remoteChart: loki
        repo: https://grafana.github.io/helm-charts
        namespace: observability
        createNamespace: true
        version: "6.40.0"
        valuesFiles: [helm/helm-values/loki.yaml]
        wait: true
        upgradeOnChange: false

      - name: tempo
        remoteChart: tempo
        repo: https://grafana.github.io/helm-charts
        namespace: observability
        version: "1.23.3"
        valuesFiles: [helm/helm-values/tempo.yaml]
        wait: true
        upgradeOnChange: false

      - name: grafana
        remoteChart: grafana
        repo: https://grafana.github.io/helm-charts
        namespace: observability
        version: "9.4.4"
        valuesFiles: [helm/helm-values/grafana.yaml]
        wait: true
        upgradeOnChange: false

      - name: otel-collector
        remoteChart: opentelemetry-collector
        repo: https://open-telemetry.github.io/opentelemetry-helm-charts
        namespace: observability
        version: "0.133.0"
        valuesFiles: [helm/helm-values/otelcol.yaml]
        wait: true
        upgradeOnChange: false

      - name: prometheus
        remoteChart: prometheus
        repo: https://prometheus-community.github.io/helm-charts
        namespace: observability
        version: "27.39.0"
        valuesFiles: [helm/helm-values/prometheus.yaml]
        wait: true
        upgradeOnChange: false
        dependsOn: ["otel-collector"]

      - name: minio
        remoteChart: minio
        repo: https://charts.min.io
        version: "5.4.0"
        namespace: minio
        createNamespace: true
        valuesFiles: [helm/helm-values/minio.yaml]
        wait: true
        upgradeOnChange: true

      - name: imgproxy
        remoteChart: imgproxy
        repo: https://helm.imgproxy.net
        version: "1.1.0"
        namespace: imgproxy
        createNamespace: true
        valuesFiles: [helm/helm-values/imgproxy.yaml]
        wait: true
        upgradeOnChange: true

      - name: ecommerce
        chartPath: helm/ecommerce-go-service
        namespace: dev
        createNamespace: true
        skipBuildDependencies: false
        wait: true
        upgradeOnChange: false
        setValueTemplates:
          ecommerce-product-service.image.tag:               "{{.IMAGE_TAG_sokol111_ecommerce_product_service}}"
          ecommerce-category-service.image.tag:              "{{.IMAGE_TAG_sokol111_ecommerce_category_service}}"
          ecommerce-product-query-service.image.tag:         "{{.IMAGE_TAG_sokol111_ecommerce_product_query_service}}"
          ecommerce-category-query-service.image.tag:        "{{.IMAGE_TAG_sokol111_ecommerce_category_query_service}}"

          ecommerce-product-service.migrator.image:          "{{.IMAGE_REPO_sokol111_ecommerce_product_service_migrator}}:{{.IMAGE_TAG_sokol111_ecommerce_product_service_migrator}}"
          ecommerce-category-service.migrator.image:         "{{.IMAGE_REPO_sokol111_ecommerce_category_service_migrator}}:{{.IMAGE_TAG_sokol111_ecommerce_category_service_migrator}}"
          ecommerce-product-query-service.migrator.image:    "{{.IMAGE_REPO_sokol111_ecommerce_product_query_service_migrator}}:{{.IMAGE_TAG_sokol111_ecommerce_product_query_service_migrator}}"
          ecommerce-category-query-service.migrator.image:   "{{.IMAGE_REPO_sokol111_ecommerce_category_query_service_migrator}}:{{.IMAGE_TAG_sokol111_ecommerce_category_query_service_migrator}}"

          ecommerce-product-service.commonsMigrator.image:   "{{.IMAGE_REPO_sokol111_ecommerce_commons_migrator}}:{{.IMAGE_TAG_sokol111_ecommerce_commons_migrator}}"
          ecommerce-category-service.commonsMigrator.image:  "{{.IMAGE_REPO_sokol111_ecommerce_commons_migrator}}:{{.IMAGE_TAG_sokol111_ecommerce_commons_migrator}}"
          ecommerce-product-query-service.commonsMigrator.image: "{{.IMAGE_REPO_sokol111_ecommerce_commons_migrator}}:{{.IMAGE_TAG_sokol111_ecommerce_commons_migrator}}"
          ecommerce-category-query-service.commonsMigrator.image: "{{.IMAGE_REPO_sokol111_ecommerce_commons_migrator}}:{{.IMAGE_TAG_sokol111_ecommerce_commons_migrator}}"