# Production values for ecommerce-catalog-service
fullnameOverride: ecommerce-catalog-service

image:
  repository: ghcr.io/sokol111/ecommerce-catalog-service
  tag: "0.1.6"
  pullPolicy: IfNotPresent

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

config: |
  mongo:
    database: catalog
    max-pool-size: 20
  kafka:
    schema-registry:
      auto-register-schemas: true
  observability:
    tracing:
      enabled: true
    metrics:
      enabled: true

env:
  - name: APP_ENV
    value: "production"
  - name: CONFIG_FILE
    value: "/configs/config.yaml"
  - name: MONGO__CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: mongodb-credentials
        key: connection-string
  # Auth
  - name: SECURITY__TOKEN__PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        name: auth-keys
        key: public-key
  # Kafka (Redpanda)
  - name: KAFKA__BROKERS
    value: "redpanda.prod.svc.cluster.local:9093"
  - name: KAFKA__SCHEMA_REGISTRY__URL
    value: "http://redpanda.prod.svc.cluster.local:8081"
  # Observability
  - name: OBSERVABILITY__OTEL_COLLECTOR_ENDPOINT
    value: "alloy.observability.svc.cluster.local:4317"
  - name: APP_SERVICE_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['app.kubernetes.io/name']
  - name: APP_SERVICE_VERSION
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['app.kubernetes.io/version']
