{{- $sa := .Values.serviceAccount | default dict }}
{{- $gsa := dict }}
{{- if .Values.global }}
  {{- $gsa = .Values.global.serviceAccount | default dict }}
{{- end }}
{{- $create := (hasKey .Values "serviceAccount") | ternary $sa.create $gsa.create }}

{{- if $create }}
{{ include "shared.serviceAccount" (dict
  "name" (include "template.serviceAccountName" .)
  "Values" .Values
  "Labels" (include "template.labels" . | fromYaml)
) }}
{{- end }}