# Default values for ecommerce-product-service
nameOverride: ""
fullnameOverride: ""

image:
  repository: sokol111/ecommerce-product-service
  tag: "dev"
  pullPolicy: IfNotPresent
  digest: ""

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ecommerce-product-service.local
  tls: []

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /health/live
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 2

readinessProbe:
  httpGet:
    path: /health/ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}

volumes: []
volumeMounts: []

env: []

# Init containers configuration
initContainers:
  - name: migrate
    image: "sokol111/ecommerce-product-service-migrator:dev"
    command: ["/bin/sh", "-c"]
    args:
      - migrate -path=/migrations -database "mongodb://mongo:27017/product?replicaSet=rs0&w=majority&retryWrites=true&x-advisory-locking=true&x-migrations-collection=schema_migrations" up
