apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ecommerce-go-dev

build:
  tagPolicy: { sha256: {} }
  local:
    push: false
    useBuildkit: true
    concurrency: 6
  artifacts:
    - image: sokol111/ecommerce-product-service
      context: /home/ihsokolo/projects/ecommerce
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.local
        buildArgs:
          SERVICE_DIR: ecommerce-product-service
          COMMONS_DIR: ecommerce-commons
    - image: sokol111/ecommerce-category-service
      context: /home/ihsokolo/projects/ecommerce
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.local
        buildArgs:
          SERVICE_DIR: ecommerce-category-service
          COMMONS_DIR: ecommerce-commons
    - image: sokol111/ecommerce-product-query-service
      context: /home/ihsokolo/projects/ecommerce
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.local
        buildArgs:
          SERVICE_DIR: ecommerce-product-query-service
          COMMONS_DIR: ecommerce-commons
    - image: sokol111/ecommerce-category-query-service
      context: /home/ihsokolo/projects/ecommerce
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.local
        buildArgs:
          SERVICE_DIR: ecommerce-category-query-service
          COMMONS_DIR: ecommerce-commons
    - image: sokol111/ecommerce-image-service
      context: /home/ihsokolo/projects/ecommerce
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.local
        buildArgs:
          SERVICE_DIR: ecommerce-image-service
          COMMONS_DIR: ecommerce-commons
    - image: sokol111/ecommerce-admin-ui
      context: /home/ihsokolo/projects/ecommerce/ecommerce-admin-ui
      docker:
        dockerfile: ../ecommerce-infrastructure/docker/Dockerfile.nextjs

portForward:
  - resourceType: service
    resourceName: ecommerce-ecommerce-product-service
    namespace: dev
    port: 2345
    localPort: 2345
  - resourceType: service
    resourceName: ecommerce-ecommerce-category-service
    namespace: dev
    port: 2345
    localPort: 2346
  - resourceType: service
    resourceName: ecommerce-ecommerce-product-query-service
    namespace: dev
    port: 2345
    localPort: 2347
  - resourceType: service
    resourceName: ecommerce-ecommerce-category-query-service
    namespace: dev
    port: 2345
    localPort: 2348
  - resourceType: service
    resourceName: ecommerce-ecommerce-image-service
    namespace: dev
    port: 2345
    localPort: 2349
  - resourceType: service
    resourceName: ecommerce-ecommerce-admin-ui
    namespace: dev
    port: 3000
    localPort: 3000

deploy:
  kubeContext: k3d-dev-cluster
  helm:
    releases:
      - name: ecommerce
        chartPath: helm/ecommerce-go-service
        namespace: dev
        createNamespace: true
        skipBuildDependencies: false
        wait: true
        upgradeOnChange: true
        valuesFiles:
          - helm/ecommerce-go-service/values.debug.yaml
        setValueTemplates:
          ecommerce-product-service.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_product_service}}"
          ecommerce-category-service.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_category_service}}"
          ecommerce-product-query-service.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_product_query_service}}"
          ecommerce-category-query-service.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_category_query_service}}"
          ecommerce-image-service.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_image_service}}"
          ecommerce-admin-ui.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_admin_ui}}"
