apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ecommerce-go-dev

build:
  tagPolicy: { sha256: {} }
  local:
    push: false
    useBuildkit: true
    concurrency: 4
  artifacts:
    - image: sokol111/ecommerce-product-service
      context: /home/ihsokolo/projects/ecommerce
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.localdebug
        buildArgs:
          SERVICE_DIR: ecommerce-product-service
          COMMONS_DIR: ecommerce-commons
    - image: sokol111/ecommerce-category-service
      context: /home/ihsokolo/projects/ecommerce
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.localdebug
        buildArgs:
          SERVICE_DIR: ecommerce-category-service
          COMMONS_DIR: ecommerce-commons
    - image: sokol111/ecommerce-product-query-service
      context: /home/ihsokolo/projects/ecommerce
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.localdebug
        buildArgs:
          SERVICE_DIR: ecommerce-product-query-service
          COMMONS_DIR: ecommerce-commons
    - image: sokol111/ecommerce-category-query-service
      context: /home/ihsokolo/projects/ecommerce
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.localdebug
        buildArgs:
          SERVICE_DIR: ecommerce-category-query-service
          COMMONS_DIR: ecommerce-commons
    - image: sokol111/ecommerce-image-service
      context: /home/ihsokolo/projects/ecommerce
      docker:
        dockerfile: ecommerce-infrastructure/docker/Dockerfile.localdebug
        buildArgs:
          SERVICE_DIR: ecommerce-image-service
          COMMONS_DIR: ecommerce-commons

portForward:
  - resourceType: service
    resourceName: ecommerce-ecommerce-product-service
    namespace: dev
    port: 2345
    localPort: 2345
  - resourceType: service
    resourceName: ecommerce-ecommerce-category-service
    namespace: dev
    port: 2345
    localPort: 2346
  - resourceType: service
    resourceName: ecommerce-ecommerce-product-query-service
    namespace: dev
    port: 2345
    localPort: 2347
  - resourceType: service
    resourceName: ecommerce-ecommerce-category-query-service
    namespace: dev
    port: 2345
    localPort: 2348
  - resourceType: service
    resourceName: ecommerce-ecommerce-image-service
    namespace: dev
    port: 2345
    localPort: 2349

deploy:
  kubeContext: k3d-dev-cluster
  helm:
    releases:
      - name: traefik-crds
        remoteChart: traefik-crds
        repo: https://traefik.github.io/charts
        version: "1.11.0"
        namespace: traefik
        createNamespace: true
        wait: true
        upgradeOnChange: false

      - name: traefik
        remoteChart: traefik
        repo: https://traefik.github.io/charts
        version: "37.1.0"
        namespace: traefik
        valuesFiles: [helm/values/infrastructure/traefik.yaml]
        wait: true
        upgradeOnChange: false
        dependsOn: ["traefik-crds"]

      - name: otel-collector
        remoteChart: opentelemetry-collector
        repo: https://open-telemetry.github.io/opentelemetry-helm-charts
        namespace: observability
        createNamespace: true
        version: "0.133.0"
        valuesFiles: [helm/values/observability/otelcol.yaml]
        wait: true
        upgradeOnChange: false

      - name: minio
        remoteChart: minio
        repo: https://charts.min.io
        version: "5.4.0"
        namespace: minio
        createNamespace: true
        valuesFiles: [helm/values/storage/minio.yaml]
        wait: true
        upgradeOnChange: false

      - name: imgproxy
        remoteChart: imgproxy
        repo: https://helm.imgproxy.net
        version: "1.1.0"
        namespace: imgproxy
        createNamespace: true
        valuesFiles: [helm/values/misc/imgproxy.yaml]
        wait: true
        upgradeOnChange: true

      - name: ecommerce
        chartPath: helm/ecommerce-go-service
        namespace: dev
        createNamespace: true
        skipBuildDependencies: false
        wait: true
        upgradeOnChange: true
        valuesFiles:
          - helm/ecommerce-go-service/values.debug.yaml
        setValueTemplates:
          ecommerce-product-service.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_product_service}}"
          ecommerce-category-service.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_category_service}}"
          ecommerce-product-query-service.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_product_query_service}}"
          ecommerce-category-query-service.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_category_query_service}}"
          ecommerce-image-service.image.tag: "{{.IMAGE_TAG_sokol111_ecommerce_image_service}}"
