additionalArguments:
  - "--entryPoints.web.address=:80"
  - "--entryPoints.websecure.address=:443"
  - "--api.dashboard=true"
  - "--api.insecure=true"        # лише для dev! оголює дашборд
  - "--providers.kubernetesingress"

ports:
  web:
    port: 80
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    exposedPort: 443
    protocol: TCP

service:
  enabled: true
  type: LoadBalancer

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik