apiVersion: v2
name: ecommerce-go-service
description: Umbrella chart for Golang microservices
type: application
version: 0.4.0

dependencies:
  - name: shared-helpers
    version: 0.6.0
    repository: "file://../shared-helpers"
  - name: ecommerce-product-service
    version: 0.0.24
    repository: "file://../ecommerce-product-service"
  - name: ecommerce-category-service
    version: 0.0.24
    repository: "file://../ecommerce-category-service"
  - name: ecommerce-product-query-service
    version: 0.0.6
    repository: "file://../ecommerce-product-query-service"
  - name: ecommerce-category-query-service
    version: 0.0.6
    repository: "file://../ecommerce-category-query-service"
  - name: ecommerce-image-service
    version: 0.0.1
    repository: "file://../ecommerce-image-service"
