# =============================================================================
# Infrastructure Services
# =============================================================================
# MongoDB, Kafka, Schema Registry, MinIO, imgproxy

volumes:
  mongo_data:
  mongo_config:
  kafka_data:
  minio_data:

services:
  # ---------------------------------------------------------------------------
  # MongoDB (with replica set for change streams)
  # ---------------------------------------------------------------------------
  mongo:
    image: mongo:7.0.28
    container_name: mongo
    restart: unless-stopped
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - ecommerce
    healthcheck:
      test: |
        mongosh --quiet -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --eval "
          try { 
            rs.status() 
          } catch (err) { 
            rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) 
          }
        "
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # ---------------------------------------------------------------------------
  # Kafka (KRaft mode - no Zookeeper)
  # ---------------------------------------------------------------------------
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: ${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    networks:
      - ecommerce
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:29092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # ---------------------------------------------------------------------------
  # Schema Registry (Avro schemas for Kafka)
  # ---------------------------------------------------------------------------
  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.0
    container_name: schema-registry
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ecommerce
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/subjects"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------
  # MinIO (S3-compatible storage)
  # ---------------------------------------------------------------------------
  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION_NAME: us-east-1
    volumes:
      - minio_data:/data
    networks:
      - ecommerce
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  # MinIO initialization (create bucket)
  minio-init:
    image: minio/mc:RELEASE.2025-01-18T13-40-35Z
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      mc mb --ignore-existing myminio/products;
      mc anonymous set none myminio/products;
      echo 'MinIO initialized successfully';
      "
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - ecommerce
    restart: "no"

  # ---------------------------------------------------------------------------
  # imgproxy (image processing)
  # ---------------------------------------------------------------------------
  imgproxy:
    image: darthsim/imgproxy:v3.30
    container_name: imgproxy
    restart: unless-stopped
    depends_on:
      minio:
        condition: service_healthy
    environment:
      # MinIO configuration
      IMGPROXY_USE_S3: "true"
      IMGPROXY_S3_REGION: us-east-1
      IMGPROXY_S3_ENDPOINT: http://minio:9000
      IMGPROXY_S3_ENDPOINT_USE_PATH_STYLE: "true"
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minioadmin}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      # Security
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      # Features
      IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      IMGPROXY_ENFORCE_WEBP: "false"
      IMGPROXY_ENABLE_AVIF_DETECTION: "true"
      # Performance
      IMGPROXY_MAX_SRC_RESOLUTION: 50.0
      IMGPROXY_CONCURRENCY: 100
      IMGPROXY_MAX_CLIENTS: 500
      # Logging
      IMGPROXY_LOG_LEVEL: warn
    networks:
      - ecommerce
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
      interval: 10s
      timeout: 5s
      retries: 3
