# =============================================================================
# Observability Stack
# =============================================================================
# Grafana Alloy (all-in-one), Prometheus, Tempo, Loki, Grafana

volumes:
  prometheus_data:
  tempo_data:
  loki_data:
  grafana_data:

services:
  # ---------------------------------------------------------------------------
  # Grafana Alloy (OTLP receiver + log collector - all-in-one)
  # ---------------------------------------------------------------------------
  # Replaces: OpenTelemetry Collector + Promtail
  # Receives: OTLP (metrics + traces) from Go services + Docker logs
  # Exports: Prometheus (metrics), Tempo (traces), Loki (logs)
  alloy:
    image: grafana/alloy:v1.12.2
    container_name: alloy
    restart: unless-stopped
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ../config/alloy-config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      prometheus:
        condition: service_healthy
      tempo:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - ecommerce
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:12345/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ---------------------------------------------------------------------------
  # Prometheus (metrics storage)
  # ---------------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--storage.tsdb.retention.time=15d'
    volumes:
      - ../config/prometheus-config.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - ecommerce
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------
  # Tempo (distributed tracing)
  # ---------------------------------------------------------------------------
  tempo:
    image: grafana/tempo:2.9.1
    container_name: tempo
    restart: unless-stopped
    command: -config.file=/etc/tempo/config.yaml
    volumes:
      - ../config/tempo-config.yaml:/etc/tempo/config.yaml:ro
      - tempo_data:/var/tempo
    networks:
      - ecommerce
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3200/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------
  # Loki (log aggregation)
  # ---------------------------------------------------------------------------
  loki:
    image: grafana/loki:3.6.4
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ../config/loki-config.yaml:/etc/loki/config.yaml:ro
      - loki_data:/loki
    networks:
      - ecommerce
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------
  # Grafana (dashboards & visualization)
  # ---------------------------------------------------------------------------
  grafana:
    image: grafana/grafana:12.3.1
    container_name: grafana
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_healthy
      tempo:
        condition: service_healthy
      loki:
        condition: service_healthy
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_LOG_LEVEL: warn
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - ../config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ../config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ../dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    networks:
      - ecommerce
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.routers.grafana.middlewares=security-headers@docker"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
