apiVersion: v2
name: actions-webhook
description: A Helm chart for Zitadel Actions v2 permissions webhook
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: shared-helpers
    version: 0.6.0
    repository: "file://../shared-helpers"
