env:
  # Увімкнути джерело S3 (MinIO)
  IMGPROXY_USE_S3: "true"
  IMGPROXY_S3_REGION: "us-east-1"
  # Сервіс MinIO у неймспейсі minio (назва сервісу = назва релізу = "minio")
  IMGPROXY_S3_ENDPOINT: "http://minio.minio.svc.cluster.local:9000"
  IMGPROXY_S3_ENDPOINT_USE_PATH_STYLE: "true" # для MinIO

  # Креденшіали доступу до MinIO
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin123"

  IMGPROXY_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
  IMGPROXY_SALT: "1111111111111111111111111111111111111111111111111111111111111111"

  # Корисні дрібниці
  IMGPROXY_ENABLE_WEBP_DETECTION: "true" # віддавати WebP якщо браузер вміє

resources:
  serviceMonitor:
    enabled: false

  service:
    type: ClusterIP
    # port: 8080   # (не обов'язково; за замовчуванням 8080)

  ingress:
    enabled: true
    className: traefik
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: web # HTTP:80 у k3d-traefik
    hosts:
      - imgproxy.127.0.0.1.nip.io
    tls: [] # dev: без TLS
