mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

presets:
  logsCollection:
    enabled: true          # додає filelog + маунти /var/log/pods
  kubernetesAttributes:
    enabled: false

config:
  receivers:
    # прийом трейcів від сервісів (OTLP)
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    k8sattributes:
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
        labels:
          - key: app.kubernetes.io/name
            from: pod
            tag_name: service.name
          - key: app.kubernetes.io/version
            from: pod
            tag_name: service.version
          - key: app.kubernetes.io/environment
            from: pod
            tag_name: deployment.environment

    # 2) Прибрати зайві resource-атрибути (вони стають лейблами в Loki)
    resource/cleanup:
      attributes:
        - action: delete
          key: k8s.container.name
        - action: delete
          key: k8s.deployment.name
        - action: delete
          key: k8s.pod.uid
        - action: delete
          key: k8s.pod.start_time
        - action: delete
          key: k8s.node.name

    # 3) Прибрати зайві атрибути запису (CRI-похідні)
    attributes/cleanup:
      actions:
        - action: delete
          key: log.file.path
        - action: delete
          key: log.iostream
        - action: delete
          key: logtag

    batch: {}

  exporters:
    # ЛОГИ → Loki (нативний OTLP/HTTP)
    otlphttp/logs:
      endpoint: http://loki.observability.svc:3100/otlp
      tls:
        insecure: true
    # ТРЕЙСИ → Tempo (OTLP/gRPC)
    otlp/tempo:
      endpoint: tempo.observability.svc:4317
      tls:
        insecure: true
    # Щоб не падала metrics-пайплайна (відправимо в debug)
    debug: {}

  service:
    pipelines:
      logs:
        receivers:  [filelog]           # filelog додається пресетом logsCollection
        processors: [k8sattributes, resource/cleanup, attributes/cleanup, batch]
        exporters:  [otlphttp/logs]
      traces:
        receivers:  [otlp]
        processors: [batch]
        exporters:  [otlp/tempo]
      metrics:
        receivers:  [otlp]              # базові метрики з OTLP
        processors: [batch]
        exporters:  [debug]             # в debug, щоб не потрібні були зовнішні експортери