mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

presets:
  logsCollection:
    enabled: true          # додає filelog + маунти /var/log/pods
  kubernetesAttributes:
    enabled: true          # додає k8sattributes + потрібні RBAC

config:
  receivers:
    # прийом трейcів від сервісів (OTLP)
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}

  exporters:
    # ЛОГИ → Loki (нативний OTLP/HTTP)
    otlphttp/logs:
      endpoint: http://loki.observability.svc:3100/otlp
      tls:
        insecure: true
    # ТРЕЙСИ → Tempo (OTLP/gRPC)
    otlp/tempo:
      endpoint: tempo.observability.svc:4317
      tls:
        insecure: true
    # Щоб не падала metrics-пайплайна (відправимо в debug)
    debug: {}

  service:
    pipelines:
      logs:
        receivers:  [filelog]           # filelog додається пресетом logsCollection
        processors: [batch]
        exporters:  [otlphttp/logs]
      traces:
        receivers:  [otlp]
        processors: [batch]
        exporters:  [otlp/tempo]
      metrics:
        receivers:  [otlp]              # базові метрики з OTLP
        processors: [batch]
        exporters:  [debug]             # в debug, щоб не потрібні були зовнішні експортери