mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

presets:
  logsCollection:
    enabled: true          # додає filelog + маунти /var/log/pods
  kubernetesAttributes:
    enabled: true

config:
  receivers:
    # прийом трейcів від сервісів (OTLP)
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    k8sattributes:
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.deployment.name
        labels:
          - key: app.kubernetes.io/name
            tag_name: service.name
          - key: app.kubernetes.io/version
            tag_name: service.version
          - key: app.kubernetes.io/environment
            tag_name: deployment.environment
      filter:
        node_from_env_var: K8S_NODE_NAME
      passthrough: false
      pod_association:
        - sources:
            - from: resource_attribute
              name: k8s.pod.ip
        - sources:
            - from: resource_attribute
              name: k8s.pod.uid
        - sources:
            - from: connection
        - sources:                       # <-- ключ: додаткове правило
            - from: resource_attribute
              name: k8s.pod.name
            - from: resource_attribute
              name: k8s.namespace.name

    attributes/derive-service:
      actions:
        - action: insert
          key: service.name
          from_attribute: k8s.deployment.name
        - action: insert
          key: service.name
          from_attribute: k8s.container.name

    resource/cleanup:
      attributes:
        - action: delete
          key: k8s.container.name
        - action: delete
          key: k8s.deployment.name
        - action: delete
          key: k8s.pod.uid
        - action: delete
          key: k8s.pod.start_time
        - action: delete
          key: k8s.node.name

    # 3) Прибрати зайві атрибути запису (CRI-похідні)
    attributes/cleanup:
      actions:
        - action: delete
          key: log.file.path
        - action: delete
          key: log.iostream
        - action: delete
          key: logtag

    batch: {}

  exporters:
    debug/logs:
      verbosity: detailed
    # ЛОГИ → Loki (нативний OTLP/HTTP)
    otlphttp/logs:
      endpoint: http://loki.observability.svc:3100/otlp
      tls:
        insecure: true
    # ТРЕЙСИ → Tempo (OTLP/gRPC)
    otlp/tempo:
      endpoint: tempo.observability.svc:4317
      tls:
        insecure: true
    # Щоб не падала metrics-пайплайна (відправимо в debug)
    debug: {}

  service:
    pipelines:
      logs:
        receivers:  [filelog]           # filelog додається пресетом logsCollection
        processors: [k8sattributes, attributes/derive-service, resource/cleanup, attributes/cleanup, batch]
        exporters:  [otlphttp/logs, debug/logs]
      traces:
        receivers:  [otlp]
        processors: [batch]
        exporters:  [otlp/tempo]
      metrics:
        receivers:  [otlp]              # базові метрики з OTLP
        processors: [batch]
        exporters:  [debug]             # в debug, щоб не потрібні були зовнішні експортери