# Default values for ecommerce-product-query-service
nameOverride: ""
fullnameOverride: ""

migratorImage: "sokol111/ecommerce-product-query-service-migrator:dev"
dbName: "product-query"

image:
  repository: sokol111/ecommerce-product-query-service
  tag: "dev"
  pullPolicy: IfNotPresent
  digest: ""

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ecommerce-product-query-service.local
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /health/live
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 2

readinessProbe:
  httpGet:
    path: /health/ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

replicaCount: 1

nodeSelector: {}
tolerations: []
affinity: {}

volumes: []
volumeMounts: []
env: []
